### ISSUE TITLE
Craftable mob spawner

### ISSUE THREAD

**Issue by iAerosoft** [CAD97/SpawnerCraft#15]
I enabled craftable spawners in the config file but it's not letting me craft them. I'm assuming the recipe is 8 iron bars in a crafting table in a chest formation. I also do not see a recipe for it anywhere on the mod website. So either I have the wrong recipe or it's not working.

**Comment by CAD97** [comment]
It's working for me:

![2017-06-15_15 17 21](https://user-images.githubusercontent.com/5992217/27197841-cd659538-51dd-11e7-9f90-5c709acf73a9.png)

(I'm working on making the discoverability better... slowly...)

Due to the way Forge works, we require a restart of Minecraft before the recipe is added/removed. Did you make sure to restart Minecraft?

If the issue persists, please tell me which version you are running, so I can make sure that I'm testing the same version on my machine.
