### ISSUE TITLE
Can't craft agglomeration of mobs.

### ISSUE THREAD

**Issue by Duffenstein** [CAD97/SpawnerCraft#18]
Essence can be collected but not crafted into agglomerations.  I tried several different mob types and created a new world to test with the same results.  I was able to craft the mob fishing rod but cannot craft mob spawners themselves (they do drop when mined).  I have several other mods installed but also tried uninstalling the rest of them, again, same results.  

Let me know what/if any files would help.  
![2017-06-23_01 21 53](https://user-images.githubusercontent.com/29648874/27468059-6a095f82-57b5-11e7-9338-7854766bb335.png)

**Comment by Duffenstein** [comment]
I changed the config for craftable spawners and that does work now.  MC 1.11.2

**Comment by CAD97** [comment]
Depending on the version you are using there may be a bug meaning the
essence can only be crafted in a 2x2 crafting grid (like your (survival)
inventory).

That is fixed in the working tree but has yet to see a release. I also need
to test to see which versions need the fix I added. Right now I'm away from
my development machine and cannot do so.

**Comment by Duffenstein** [comment]
Crafting in the inventory box does work, thanks.  Version is 4.0.0

**Comment by CAD97** [comment]
This is fixed properly in the latest 4.0.0b2
